// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_queries.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createAuditLog = `-- name: CreateAuditLog :execresult
INSERT INTO audit_logs (task_id, action, actor, details)
VALUES (COALESCE(?, 'system'), ?, ?, ?)
`

type CreateAuditLogParams struct {
	Column1 interface{}     `json:"column_1"`
	Action  string          `json:"action"`
	Actor   string          `json:"actor"`
	Details json.RawMessage `json:"details"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAuditLog,
		arg.Column1,
		arg.Action,
		arg.Actor,
		arg.Details,
	)
}
