// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cursor_queries.sql

package store

import (
	"context"
)

const getCursor = `-- name: GetCursor :one
SELECT cursor_value FROM sync_cursors 
WHERE task_id = ? AND table_name = ?
`

type GetCursorParams struct {
	TaskID    string `json:"task_id"`
	TableName string `json:"table_name"`
}

func (q *Queries) GetCursor(ctx context.Context, arg GetCursorParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getCursor, arg.TaskID, arg.TableName)
	var cursor_value string
	err := row.Scan(&cursor_value)
	return cursor_value, err
}

const upsertCursor = `-- name: UpsertCursor :exec
INSERT INTO sync_cursors (task_id, table_name, cursor_field, cursor_value, updated_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(task_id, table_name) DO UPDATE SET
    cursor_value = excluded.cursor_value,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertCursorParams struct {
	TaskID      string `json:"task_id"`
	TableName   string `json:"table_name"`
	CursorField string `json:"cursor_field"`
	CursorValue string `json:"cursor_value"`
}

func (q *Queries) UpsertCursor(ctx context.Context, arg UpsertCursorParams) error {
	_, err := q.db.ExecContext(ctx, upsertCursor,
		arg.TaskID,
		arg.TableName,
		arg.CursorField,
		arg.CursorValue,
	)
	return err
}
