// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dlq_queries.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createDLQEntry = `-- name: CreateDLQEntry :execresult
INSERT INTO sync_dlq (task_id, table_name, failed_row, error_msg, retry_count)
VALUES (?, ?, ?, ?, 0)
`

type CreateDLQEntryParams struct {
	TaskID    string          `json:"task_id"`
	TableName string          `json:"table_name"`
	FailedRow json.RawMessage `json:"failed_row"`
	ErrorMsg  string          `json:"error_msg"`
}

func (q *Queries) CreateDLQEntry(ctx context.Context, arg CreateDLQEntryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDLQEntry,
		arg.TaskID,
		arg.TableName,
		arg.FailedRow,
		arg.ErrorMsg,
	)
}
