// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"encoding/json"
)

type AuditLog struct {
	ID        int64           `json:"id"`
	TaskID    string          `json:"task_id"`
	Action    string          `json:"action"`
	Actor     string          `json:"actor"`
	Details   json.RawMessage `json:"details"`
	CreatedAt sql.NullTime    `json:"created_at"`
}

type SyncCursor struct {
	TaskID      string       `json:"task_id"`
	TableName   string       `json:"table_name"`
	CursorField string       `json:"cursor_field"`
	CursorValue string       `json:"cursor_value"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type SyncDlq struct {
	ID         int64           `json:"id"`
	TaskID     string          `json:"task_id"`
	TableName  string          `json:"table_name"`
	FailedRow  json.RawMessage `json:"failed_row"`
	ErrorMsg   string          `json:"error_msg"`
	RetryCount sql.NullInt64   `json:"retry_count"`
	CreatedAt  sql.NullTime    `json:"created_at"`
}

type Task struct {
	ID                 string          `json:"id"`
	Name               string          `json:"name"`
	Status             string          `json:"status"`
	SourceDsnEncrypted string          `json:"source_dsn_encrypted"`
	TargetDsnEncrypted string          `json:"target_dsn_encrypted"`
	MappingConfig      json.RawMessage `json:"mapping_config"`
	CronExpr           string          `json:"cron_expr"`
	CreatedAt          sql.NullTime    `json:"created_at"`
	UpdatedAt          sql.NullTime    `json:"updated_at"`
}
