// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_queries.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createTask = `-- name: CreateTask :execresult
INSERT INTO tasks (id, name, status, source_dsn_encrypted, target_dsn_encrypted, mapping_config, cron_expr)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	ID                 string          `json:"id"`
	Name               string          `json:"name"`
	Status             string          `json:"status"`
	SourceDsnEncrypted string          `json:"source_dsn_encrypted"`
	TargetDsnEncrypted string          `json:"target_dsn_encrypted"`
	MappingConfig      json.RawMessage `json:"mapping_config"`
	CronExpr           string          `json:"cron_expr"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTask,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.SourceDsnEncrypted,
		arg.TargetDsnEncrypted,
		arg.MappingConfig,
		arg.CronExpr,
	)
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, name, status, source_dsn_encrypted, target_dsn_encrypted, mapping_config, cron_expr, created_at, updated_at FROM tasks WHERE id = ?
`

func (q *Queries) GetTaskByID(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.SourceDsnEncrypted,
		&i.TargetDsnEncrypted,
		&i.MappingConfig,
		&i.CronExpr,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, name, status, cron_expr, created_at, updated_at FROM tasks ORDER BY created_at DESC
`

type ListTasksRow struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	Status    string       `json:"status"`
	CronExpr  string       `json:"cron_expr"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) ListTasks(ctx context.Context) ([]ListTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksRow
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CronExpr,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateTaskStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, arg.Status, arg.ID)
	return err
}
